version: "3"

services:
  gateway:
    image: ${GATEWAY_DOCKER_REPO}:${GATEWAY_DOCKER_VERSION}
    environment:
      CODECOV_API_HOST: api.codecov.io
      CODECOV_API_PORT: 443
      CODECOV_API_SCHEME: https
      CODECOV_API_HOST_HEADER: api.codecov.io
      CODECOV_IA_HOST: api.codecov.io
      CODECOV_IA_PORT: 443
      CODECOV_IA_SCHEME: https
      CODECOV_IA_HOST_HEADER: api.codecov.io
      CODECOV_DEFAULT_HOST: qa.codecov.dev
      CODECOV_DEFAULT_PORT: 443
      CODECOV_DEFAULT_SCHEME: https
      CODECOV_DEFAULT_HOST_HEADER: qa.codecov.dev
      #CODECOV_GATEWAY_PROXY_MODE_ENABLED: true
      #CODECOV_GATEWAY_CHROOT_DISABLED: true
      #CODECOV_GATEWAY_SSL_ENABLED: true
    ports:
      - "8080:8080"
      - "8404:8404"
      #- "8443:8443"
#    volumes:
#      - /path/to/cert/cert.crt:/etc/codecov/ssl/certs/cert.crt