version: "3"

services:
  gateway:
    image: us-docker.pkg.dev/genuine-polymer-165712/codecov/enterprise-gateway
    environment:
      CODECOV_API_HOST: api.codecov.io
      CODECOV_API_PORT: 443
      CODECOV_API_SCHEME: https
      CODECOV_API_HOST_HEADER: api.codecov.io
      CODECOV_IA_HOST: api.codecov.io
      CODECOV_IA_PORT: 443
      CODECOV_IA_SCHEME: https
      CODECOV_IA_HOST_HEADER: api.codecov.io
      CODECOV_FRONTEND_HOST: qa.codecov.dev
      CODECOV_FRONTEND_PORT: 443
      CODECOV_FRONTEND_SCHEME: https
      CODECOV_FRONTEND_HOST_HEADER: qa.codecov.dev
    ports:
      - "8080:8080"
      - "8404:8404"
