name: Build and Push to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Enable experimental docker'
        run: |
          sudo bash -c 'echo "{\"experimental\": true}" >> /etc/docker/daemon.json'
          sudo systemctl restart docker

      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/582817289294/locations/global/workloadIdentityPools/codecov-production/providers/codecov-production'
          service_account: 'codecov-prod-gh@genuine-polymer-165712.iam.gserviceaccount.com'

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      # Build the Docker image
      - name: Build
        run: |-
          make build
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |-
          make push
