name: Release Dockerhub image

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  push_to_registry:
    name: Tag Release ${{ github.head_ref }} and Push Docker image to Docker Hub
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    environment: enterprise
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Tag Release
        run: |-
          make tag.release
      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/582817289294/locations/global/workloadIdentityPools/codecov-production/providers/codecov-production'
          service_account: 'codecov-prod-gh@genuine-polymer-165712.iam.gserviceaccount.com'

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.CODECOV_DEVOPS_DOCKER_USERNAME }}
          password: ${{ secrets.CODECOV_DEVOPS_DOCKER_PASSWORD }}

      # Push the Docker image from Google Artifact Registry to Dockerhub
      - name: Publish
        run: |-
          make release